# Generated by Django 3.2.3 on 2022-07-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_kesuaninfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('dange', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=64)),
            ],
        ),
    ]
