# Generated by Django 3.2.3 on 2022-07-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_shopinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='jinhuoINFo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('factory', models.CharField(max_length=32)),
                ('shopId', models.IntegerField(default=2)),
                ('number', models.CharField(max_length=64)),
                ('sum', models.CharField(max_length=64)),
            ],
        ),
    ]
